name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20", "1.21"]
    steps:
      - name: Check out source
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go }}
      - name: Use lint cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            ~/.cache/golangci-lint
          key: go-lint-${{ matrix.go }}-${{ hashFiles('./go.sum') }}
          restore-keys: go-lint-${{ matrix.go }}
      - name: Stablilize testdata timestamps
        run: |
          bash ./.github/stablilize_testdata_timestamps.sh "${{ github.workspace }}"
      - name: Install Linters
        run: "go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.1"
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          sh ./run_tests.sh
